### ISSUE TITLE
Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by joshuabenuck** [newrelic/newrelic-php-daemon-docker#36] opened 2021-01-25 20:49 UTC
The Travis CI tests stall in the queued state and the travis-ci.org domain is being EOL'ed. Rather than invest the time to figure out how to fix the current setup, it makes sense to migrate the tests to GitHub Actions as that is what we are using for our newer repos.

**Comment by zsistla** [comment] 2022-03-08 22:21
Duplicate of https://github.com/newrelic/newrelic-php-agent/issues/367 where this issue will be tracked.

**Closed by zsistla** 2022-03-08 22:21 UTC
